name: Java Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
         

      - name: Lint Java
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: main
          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          JAVA_CHECKSTYLE_CONFIG_FILE: checkstyle_gnf.xml
          VALIDATE_JAVA_FORMATTER: false
          LINTER_RULES_PATH: .github/linters/ 
