name: Java Linting

on: [push, pull_request]

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Checkstyle
        uses: dbelyaev/action-checkstyle@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Options: google_checks.xml (default) or sun_checks.xml
          checkstyle_config: google_checks.xml 
          level: warning
          workdir: ./QREST/src
